extension_dir="C:/Users/Webisko/AppData/Local/Microsoft/WinGet/Packages/PHP.PHP.8.4_Microsoft.Winget.Source_8wekyb3d8bbwe/ext"

extension=curl
extension=fileinfo
extension=intl
extension=mbstring
extension=openssl
extension=pdo_sqlite
extension=sqlite3
extension=zip

date.timezone=Europe/Warsaw
memory_limit=512M
post_max_size=32M
upload_max_filesize=32M